app/src/Entity/Ratings.php
<?php

namespace App\Entity;

use App\Repository\RatingsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RatingsRepository::class)]
class Ratings
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Stories::class, inversedBy: 'ratings')]
    #[ORM\JoinColumn(nullable: false)]
    private $story;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'ratings')]
    private $added_by;

    #[ORM\Column(type: 'string', length: 255)]
    private $ip_hash;

    #[ORM\Column(type: 'integer')]
    private $added_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStory(): ?Stories
    {
        return $this->story;
    }

    public function setStory(?Stories $story): self
    {
        $this->story = $story;

        return $this;
    }

    public function getAddedBy(): ?User
    {
        return $this->added_by;
    }

    public function setAddedBy(?User $added_by): self
    {
        $this->added_by = $added_by;

        return $this;
    }

    public function getIpHash(): ?string
    {
        return $this->ip_hash;
    }

    public function setIpHash(string $ip_hash): self
    {
        $this->ip_hash = $ip_hash;

        return $this;
    }

    public function getAddedAt(): ?int
    {
        return $this->added_at;
    }

    public function setAddedAt(int $added_at): self
    {
        $this->added_at = $added_at;

        return $this;
    }
}

app/src/Controller/SiteController.php
<?php

namespace App\Controller;

use App\Repository\StoriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SiteController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(StoriesRepository $sr): Response
    {
        $stories = $sr->findStories(10, 0, 1);
        return $this->render('site/index.html.twig', [
            'stories' => $stories,
        ]);
    }

    #[Route('/waiting-room', name: 'waiting_room')]
    public function waitingRoom(StoriesRepository $sr): Response
    {
        $stories = $sr->findStories(10, 0, 0);
        return $this->render('site/index.html.twig', [
            'stories' => $stories,
        ]);
    }

    #[Route('/most-popular', name: 'most_popular')]
    public function mostPopular(StoriesRepository $sr): Response
    {
        $stories = $sr->findMostPopularStories(10, 0);
        return $this->render('site/index.html.twig', [
            'stories' => $stories,
        ]);
    }
}

app/templates/site/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SiteController!{% endblock %}

{% block body %}

    <div class="container mt-5 mb-5">
        <div class="row justify-content-between">
            <div class="col-md-9">
                <div class="container-fluid p-0">
                    <div class="row">
                        <div class="col-md-11">

                            {% if stories is empty %}

                                <h4 class="text-center text-muted">
                                    No stories could be found.<br>
                                    Come back here later.
                                </h4>

                            {% else %}

                            {% for item in stories %}

                                <div class="row story-card justify-content-between shadow-3 pt-4 pb-2 mt-4" story-id="{{ item.id }}">
                                    <div class="col-md-auto">
                                        <h3>
                                            {{ item.title }}
                                        </h3>
                                    </div>
                                    <div class="col-md-auto text-end text-muted">
                                        {{ item.addedAt|date }}
                                    </div>
                                    <div class="col-md-12">
                                        <p class="story-content mb-0">
                                            {{ item.content }}
                                        </p>
                                        <div class="row mt-2 story-buttons">
                                            <div class="col-md-4 add-plus-section">
                                                <button type="button" class="btn btn-success btn-floating add-plus">
                                                    <i class="fas fa-plus"></i>
                                                </button>
                                                <span>
                                                    {{ item.rating }}
                                                </span>
                                            </div>
                                            <div class="col-md-4 text-center mt-2">
                                            </div>
                                            <div class="col-md-12 comment-section d-none">
                                                {% if (app.user) %}
                                                <form class="mt-4 add-comment">
                                                    <div class="form-outline">
                                                        <textarea class="form-control" id="content" name="content" rows="4" required></textarea>
                                                        <label class="form-label" for="content">Message</label>
                                                    </div>
                                                    <div class="w-100 text-end">
                                                        <button type="submit" class="btn btn-success mt-2">Submit</button>
                                                    </div>
                                                </form>
                                                {% endif %}
                                                <div class="comments-list"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                {% endfor %}

                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="shadow-3 p-2">
                    <a href="{{ path('add_story') }}" rel="nofollow" class="btn btn-success w-100 mt-3 mb-3">
                        Add a new story
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}